# Generated by Django 4.1.12 on 2023-10-24 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=200)),
                ("min_salary", models.IntegerField()),
                ("max_salary", models.IntegerField()),
                ("description", models.TextField(verbose_name="Описание вакансии")),
                ("experience_month", models.IntegerField(verbose_name="Опыт работы")),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата размещения"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("is_active", models.BooleanField(verbose_name="Активная вакансия")),
                ("is_draft", models.BooleanField(verbose_name="Черновик")),
                ("is_archived", models.BooleanField(verbose_name="Архивная")),
                ("is_deleted", models.BooleanField(verbose_name="Удаленная")),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "form_of_employment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.forms_of_employment",
                        verbose_name="Тип занятости",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        related_name="vacancies",
                        to="core.skills",
                        verbose_name="Навыки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Рекрутер",
                    ),
                ),
                (
                    "work_arrangement",
                    models.ManyToManyField(
                        related_name="vacancies",
                        to="core.work_arrangements",
                        verbose_name="Формат работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
    ]
