# Generated by Django 4.1.12 on 2023-10-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="company_name",
            field=models.CharField(max_length=200, verbose_name="Название компании"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="job_title",
            field=models.CharField(max_length=200, verbose_name="Название вакансии"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="max_salary",
            field=models.IntegerField(verbose_name="Зарплата до"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="min_salary",
            field=models.IntegerField(verbose_name="Зарплата от"),
        ),
    ]
