# Generated by Django 4.1.12 on 2023-10-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        (
            "vacancies",
            "0002_alter_vacancy_company_name_alter_vacancy_job_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="form_of_employment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vacancies",
                to="core.forms_of_employment",
                verbose_name="Тип занятости",
            ),
        ),
    ]
