# Generated by Django 4.1.12 on 2023-10-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_work_arrangements_educationyp_and_more"),
        ("vacancies", "0003_alter_vacancy_form_of_employment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="work_arrangement",
            field=models.ManyToManyField(
                related_name="vacancies",
                to="core.workarrangements",
                verbose_name="Формат работы",
            ),
        ),
    ]
