# Generated by Django 4.1.12 on 2023-10-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_work_arrangements_educationyp_and_more"),
        ("vacancies", "0004_alter_vacancy_work_arrangement"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="education",
            field=models.ManyToManyField(
                related_name="vacancies",
                to="core.education",
                verbose_name="Образование",
            ),
        ),
    ]
