# Generated by Django 4.1.12 on 2023-10-29 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_work_arrangements_educationyp_and_more"),
        ("vacancies", "0005_vacancy_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="education",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="vacancies",
                to="core.education",
                verbose_name="Образование",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="experience_month",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Опыт работы"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="form_of_employment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vacancies",
                to="core.formsofemployment",
                verbose_name="Тип занятости",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="vacancies",
                to="core.skills",
                verbose_name="Навыки",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="work_arrangement",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="vacancies",
                to="core.workarrangements",
                verbose_name="Формат работы",
            ),
        ),
    ]
