# Generated by Django 4.1.12 on 2023-10-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Образование",
                "verbose_name_plural": "Образования",
            },
        ),
        migrations.CreateModel(
            name="EducationYp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Курс в Яндекс Практикуме",
                "verbose_name_plural": "Курсы в Яндекс Практикуме",
            },
        ),
        migrations.CreateModel(
            name="FormsOfEmployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Тип занятости",
                "verbose_name_plural": "Типы занятости",
            },
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Навыки",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.CreateModel(
            name="StatusFromKt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Статус в карьерном треке",
                "verbose_name_plural": "Статусы в карьерном треке",
            },
        ),
        migrations.CreateModel(
            name="WorkArrangements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Формат работы",
                "verbose_name_plural": "Форматы работы",
            },
        ),
    ]
