# Generated by Django 4.1.12 on 2023-10-29 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0003_alter_vacancy_form_of_employment"),
        ("users", "0008_alter_candidate_options"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Work_arrangements",
            new_name="EducationYp",
        ),
        migrations.RenameModel(
            old_name="Forms_of_employment",
            new_name="FormsOfEmployment",
        ),
        migrations.RenameModel(
            old_name="Status_from_kt",
            new_name="StatusFromKt",
        ),
        migrations.RenameModel(
            old_name="Education_YP",
            new_name="WorkArrangements",
        ),
        migrations.AlterModelOptions(
            name="educationyp",
            options={
                "verbose_name": "Курс в Яндекс Практикуме",
                "verbose_name_plural": "Курсы в Яндекс Практикуме",
            },
        ),
        migrations.AlterModelOptions(
            name="workarrangements",
            options={
                "verbose_name": "Формат работы",
                "verbose_name_plural": "Форматы работы",
            },
        ),
    ]
