# Generated by Django 4.1.12 on 2023-10-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_work_arrangements_educationyp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
