# Generated by Django 4.1.12 on 2023-10-24 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorites",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="favorites",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="active",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Активный пользователь"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="education",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="core.education",
                verbose_name="Образование",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="education_YP",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="core.education_yp",
                verbose_name="Курс в Яндекс Практикуме",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="experience_months",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Опыт работы"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="groups",
            field=models.ManyToManyField(
                related_name="candidate_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="last_activity",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Был активен"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата размещения"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/", verbose_name="Резюме"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="telegram",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Телеграм"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="candidate_user_permissions", to="auth.permission"
            ),
        ),
        migrations.CreateModel(
            name="Ratings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="users.candidate",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
