# Generated by Django 4.1.12 on 2023-10-25 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("users", "0002_alter_candidate_form_of_employment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="core.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="status_from_kt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="core.status_from_kt",
                verbose_name="Статус в карьерном треке",
            ),
        ),
    ]
