# Generated by Django 4.1.12 on 2023-10-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("users", "0003_alter_candidate_city_alter_candidate_status_from_kt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="form_of_employment",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidate_employments",
                to="core.forms_of_employment",
                verbose_name="Тип занятости",
            ),
        ),
    ]
