# Generated by Django 4.1.12 on 2023-10-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
        ("users", "0004_alter_candidate_form_of_employment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="candidate_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidate_skills",
                to="core.skills",
                verbose_name="Навыки",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidate_user_permissions",
                to="auth.permission",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="work_arrangement",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidate_works",
                to="core.work_arrangements",
                verbose_name="Формат работы",
            ),
        ),
    ]
