# Generated by Django 4.1.12 on 2023-10-25 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_candidate_groups_alter_candidate_skills_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorites",
            options={"verbose_name": "Избранное", "verbose_name_plural": "Избранное"},
        ),
        migrations.AlterModelOptions(
            name="ratings",
            options={"verbose_name": "Рейтинг", "verbose_name_plural": "Рейтинг"},
        ),
    ]
