# Generated by Django 4.1.12 on 2023-10-27 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_favorites_options_alter_ratings_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorites",
            unique_together={("candidate", "recruiter")},
        ),
    ]
