# Generated by Django 4.1.12 on 2023-10-27 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_favorites_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Соискатель",
                "verbose_name_plural": "Соискатели",
            },
        ),
    ]
