# Generated by Django 4.1.12 on 2023-10-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_candidate_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="job_title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Название должности"
            ),
        ),
    ]
