# Generated by Django 4.1.12 on 2023-10-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_candidate_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="max_salary",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Зарплата до"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="min_salary",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Зарплата от"
            ),
        ),
    ]
