# Generated by Django 4.1.12 on 2023-10-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_work_arrangements_educationyp_and_more"),
        ("users", "0008_alter_candidate_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="education_YP",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="core.educationyp",
                verbose_name="Курс в Яндекс Практикуме",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="work_arrangement",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidate_works",
                to="core.workarrangements",
                verbose_name="Формат работы",
            ),
        ),
    ]
